# Generated by Django 3.2.7 on 2021-09-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('modelName', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('rom', models.FloatField()),
                ('processor', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('image', models.FileField(blank=True, upload_to='document/')),
            ],
        ),
    ]
